[2020-09-17 00:11:39,527] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 00:11:46,216] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body)
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:11:46,221] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:11:47,722] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body)
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:11:47,723] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:11:48,545] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body)
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:11:48,546] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:11:56,282] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body)
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:11:56,290] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:11:57,150] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body)
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:11:57,151] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:12:50,478] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 00:12:51,360] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 00:12:57,673] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body.decode())
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:12:57,680] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:12:59,030] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body.decode())
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:12:59,031] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:12:59,711] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body.decode())
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:12:59,712] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 00:12:59,896] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_resu_process
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 108, in get_resu_process
    req_para = json.loads(req.body.decode())
  File "/Applications/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-09-17 00:12:59,898] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_resu_process?work_id=ad854c895401a84cfcb32b1d46922a0b HTTP/1.1" 500 145
[2020-09-17 09:07:58,176] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:08:03,994] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 67
[2020-09-17 09:08:04,813] [log.py:230] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-09-17 09:08:04,813] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-09-17 09:09:23,561] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST / HTTP/1.1" 200 67
[2020-09-17 09:09:30,835] [view.py:84] [view:warn_realtion] [ERROR]- [e69f69dc45d309802771c456b0377557]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:09:30,842] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:10:52,249] [view.py:84] [view:warn_realtion] [ERROR]- [0687fae130e255477d2f618d536f98b8]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:10:52,252] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://10.196.135.137:8111/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:10:53,517] [view.py:84] [view:warn_realtion] [ERROR]- [a4e256756e95b8e74ab156f25b0ea35e]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:10:53,518] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://10.196.135.137:8111/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:12:01,112] [view.py:84] [view:warn_realtion] [ERROR]- [84dfd1c13769ffe14833cd8bb15a0926]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:12:01,113] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://0.0.0.0:12002/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:12:03,232] [view.py:84] [view:warn_realtion] [ERROR]- [89945efe39d136f8007873974ac47fb1]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:12:03,232] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://0.0.0.0:12002/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:17:07,005] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:17:11,625] [view.py:84] [view:warn_realtion] [ERROR]- [10ae146b4d2fee54db7ec898e0aec185]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:17:11,627] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://0.0.0.0:12002/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:23:19,382] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:23:28,671] [view.py:86] [view:warn_realtion] [ERROR]- [900df6b18cf807f49a018c3bcc0b05f3]:name 'warn_data_url' is not defined
[2020-09-17 09:23:28,672] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow?warn_data_url=http://0.0.0.0:12002/static/csv/warn_tail_30w.csv HTTP/1.1" 200 66
[2020-09-17 09:24:18,106] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:24:18,980] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:24:30,703] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:24:43,648] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /?sss=22222 HTTP/1.1" 200 67
[2020-09-17 09:24:43,767] [log.py:230] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-09-17 09:24:43,767] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-09-17 09:25:15,793] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow?sss=22222 HTTP/1.1" 200 67
[2020-09-17 09:25:34,324] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:25:34,846] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:27:48,155] [view.py:88] [view:warn_realtion] [ERROR]- [0a20e241e12c13381fb68ab1f7b1b5b5]:name 'warn_data_url' is not defined
[2020-09-17 09:27:48,157] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:28:46,530] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:28:47,448] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:28:51,293] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow?sss=22222 HTTP/1.1" 200 67
[2020-09-17 09:28:51,347] [log.py:230] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-09-17 09:28:51,348] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-09-17 09:29:01,048] [view.py:88] [view:warn_realtion] [ERROR]- [b07fcbd3c961f49fab17f2b24b8010ea]:name 'warn_data_url' is not defined
[2020-09-17 09:29:01,049] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:29:10,157] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_flow
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 28, in warn_realtion
    if req.method == "POST" and req.body != None:
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/http/request.py", line 316, in body
    raise RawPostDataException("You cannot access body after reading from request's data stream")
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
[2020-09-17 09:29:10,168] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_flow HTTP/1.1" 500 145
[2020-09-17 09:29:26,117] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:29:27,010] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:29:42,543] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:29:43,209] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:29:52,361] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:29:53,088] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:30:04,845] [view.py:88] [view:warn_realtion] [ERROR]- [689337f5ff5ac4c8350bd3ed36c7dd3b]:name 'warn_data_url' is not defined
[2020-09-17 09:30:04,847] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:30:39,914] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:30:40,465] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:30:43,893] [view.py:88] [view:warn_realtion] [ERROR]- [877d78a316a203da384ba0dad29c2cd4]:'warn_data_url'
[2020-09-17 09:30:43,894] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:32:15,841] [view.py:88] [view:warn_realtion] [ERROR]- [607270fa4e23e42d96c8dfa21966bf11]:'warn_data_url'
[2020-09-17 09:32:15,842] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 09:36:56,107] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /%0A?wwww=wwwww HTTP/1.1" 200 67
[2020-09-17 09:37:04,984] [view.py:88] [view:warn_realtion] [ERROR]- [0c1d7c56d877fd156b290170680cbf2c]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:37:04,985] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow%0A?wwww=wwwww HTTP/1.1" 200 66
[2020-09-17 09:37:12,010] [view.py:88] [view:warn_realtion] [ERROR]- [3f6518410011df0e3977ffe89297ae13]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:37:12,011] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow%0A?wwww=wwwww HTTP/1.1" 200 66
[2020-09-17 09:37:26,910] [view.py:88] [view:warn_realtion] [ERROR]- [61e6cb691bdcc7ed7b7d56967aa50fcc]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:37:26,911] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow%0A HTTP/1.1" 200 66
[2020-09-17 09:37:51,429] [view.py:88] [view:warn_realtion] [ERROR]- [4bb9464d0484c3dfebaf2f34afa089dd]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:37:51,430] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow%0A HTTP/1.1" 200 66
[2020-09-17 09:38:13,937] [view.py:88] [view:warn_realtion] [ERROR]- [e0e568033f9fa6a32085f89e4f1cef28]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 09:38:13,938] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow%0A?{%22zzz%22=%22zzzzzzzzzz%22} HTTP/1.1" 200 66
[2020-09-17 09:39:11,429] [view.py:88] [view:warn_realtion] [ERROR]- [c7c6d24d76309f93c2d7775cd20ad0a2]:Extra data: line 1 column 6 (char 5)
[2020-09-17 09:39:11,430] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 66
[2020-09-17 09:39:14,503] [view.py:88] [view:warn_realtion] [ERROR]- [d087de8be8fbc85a2f31226bf6400298]:Extra data: line 1 column 6 (char 5)
[2020-09-17 09:39:14,504] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 66
[2020-09-17 09:41:46,232] [systen_unit.py:37] [systen_unit:download_file] [ERROR]- [51ca53c5b912549cb24c747db91af338] HTTPConnectionPool(host='10.196.135.137', port=8111): Max retries exceeded with url: /static/csv/warn_tail_30w.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8fb038cfd0>: Failed to establish a new connection: [Errno 51] Network is unreachable',))
[2020-09-17 09:41:46,233] [view.py:70] [view:warn_realtion] [ERROR]- [51ca53c5b912549cb24c747db91af338]:没有告警文件下载url，或者告警文件url不合法，下载地址为http://10.196.135.137:8111/static/csv/warn_tail_30w.csv
[2020-09-17 09:41:46,234] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 81
[2020-09-17 09:43:48,059] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv HTTP/1.1" 200 30599609
[2020-09-17 09:43:48,587] [systen_unit.py:58] [systen_unit:is_good_file] [ERROR]- [270558c89f979cf9a8a1a471f39813d6]:判断CSV异常:Length mismatch: Expected axis has 5 elements, new values have 7 elements
[2020-09-17 09:43:48,597] [view.py:70] [view:warn_realtion] [ERROR]- [270558c89f979cf9a8a1a471f39813d6]:没有告警文件下载url，或者告警文件url不合法，下载地址为http://0.0.0.0:12002/static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv
[2020-09-17 09:43:48,598] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 81
[2020-09-17 09:43:57,114] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv HTTP/1.1" 200 30599609
[2020-09-17 09:43:57,588] [systen_unit.py:58] [systen_unit:is_good_file] [ERROR]- [75ea06b915c2753aaea1d83447095f65]:判断CSV异常:Length mismatch: Expected axis has 5 elements, new values have 7 elements
[2020-09-17 09:43:57,598] [view.py:70] [view:warn_realtion] [ERROR]- [75ea06b915c2753aaea1d83447095f65]:没有告警文件下载url，或者告警文件url不合法，下载地址为http://0.0.0.0:12002/static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv
[2020-09-17 09:43:57,599] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 81
[2020-09-17 09:44:25,024] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:44:26,193] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:44:31,676] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv HTTP/1.1" 200 30599609
[2020-09-17 09:44:32,170] [systen_unit.py:58] [systen_unit:is_good_file] [ERROR]- [9078e96169e9d4ec2675aa416eda4b06]:判断CSV异常:Length mismatch: Expected axis has 5 elements, new values have 7 elements
[2020-09-17 09:44:32,187] [view.py:63] [view:warn_realtion] [ERROR]- [9078e96169e9d4ec2675aa416eda4b06]:没有告警文件下载url，或者告警文件url不合法，下载地址为http://0.0.0.0:12002/static/upload/67c35597-7cc2-45ab-8fe5-64ba13f09fe0.csv
[2020-09-17 09:44:32,190] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 81
[2020-09-17 09:45:03,124] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:45:04,051] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:45:12,516] [view.py:71] [view:warn_realtion] [ERROR]- [4a001f1638a6e0138f50ffe4729fbdb3]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:45:12,518] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:45:16,409] [view.py:71] [view:warn_realtion] [ERROR]- [ab12c5026367a5fdb20adc7a5dd617a2]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:45:16,409] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:45:26,487] [view.py:71] [view:warn_realtion] [ERROR]- [dc537478b73bd064933b6d442f69c2d1]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:45:26,488] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:45:53,532] [log.py:230] [log:log_response] [WARNING]- Not Found: /uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:45:53,533] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /uploads/lteFlowOfCity5Min_anshun_guanling.csv HTTP/1.1" 404 179
[2020-09-17 09:45:54,556] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:45:55,419] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:46:16,513] [log.py:230] [log:log_response] [WARNING]- Not Found: /uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:46:16,516] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /uploads/lteFlowOfCity5Min_anshun_guanling.csv HTTP/1.1" 404 179
[2020-09-17 09:46:43,180] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 67
[2020-09-17 09:47:09,048] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:47:12,291] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:47:14,558] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:47:46,578] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:47:46,655] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:47:47,557] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:47:50,495] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:47:53,288] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:48:13,833] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:48:29,535] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:48:33,138] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:48:36,257] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:10,539] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:50:11,297] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:50:13,922] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:15,136] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:15,833] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:31,611] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:31,784] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:50:32,337] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:50:33,964] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:35,021] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:35,528] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:36,068] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:50,890] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:50:51,543] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:50:54,004] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:54,864] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:55,645] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:50:56,520] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /get_flow? HTTP/1.1" 200 67
[2020-09-17 09:51:00,407] [view.py:72] [view:warn_realtion] [ERROR]- [1d345e456da50591bda933e408517273]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:00,410] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:51:02,707] [view.py:72] [view:warn_realtion] [ERROR]- [37205347ca9495c43577d1cada1ca113]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:02,708] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:51:03,742] [view.py:72] [view:warn_realtion] [ERROR]- [7bd57da2bf02e9bed178620d77cf1353]:告警文件下载失败，或者告警文件不符合要求，下载地址为http://0.0.0.0:12002/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:03,742] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:51:54,713] [view.py:72] [view:warn_realtion] [ERROR]- [5ca748723a4e21f73be66a80bc6e5294]:告警文件下载失败，或者告警文件不符合要求，下载地址为uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:54,714] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:51:56,765] [view.py:72] [view:warn_realtion] [ERROR]- [5869201e7683d37440f8708921556743]:告警文件下载失败，或者告警文件不符合要求，下载地址为uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:56,766] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:51:59,311] [view.py:72] [view:warn_realtion] [ERROR]- [fe6256d2903b3f50df88871c9fb9a6d4]:告警文件下载失败，或者告警文件不符合要求，下载地址为uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:51:59,312] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow? HTTP/1.1" 200 74
[2020-09-17 09:54:58,614] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 67
[2020-09-17 09:54:59,267] [log.py:230] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-09-17 09:54:59,268] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-09-17 09:58:14,293] [log.py:230] [log:log_response] [WARNING]- Not Found: //Users/fengdong/PycharmProjects/flowpredict000/flowpredict/uploads
[2020-09-17 09:58:14,294] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET //Users/fengdong/PycharmProjects/flowpredict000/flowpredict/uploads HTTP/1.1" 404 179
[2020-09-17 09:58:24,669] [log.py:230] [log:log_response] [WARNING]- Not Found: //Users/fengdong/PycharmProjects/flowpredict000/flowpredict/uploads/lteFlowOfCity5Min_anshun_guanling.csv
[2020-09-17 09:58:24,669] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET //Users/fengdong/PycharmProjects/flowpredict000/flowpredict/uploads/lteFlowOfCity5Min_anshun_guanling.csv HTTP/1.1" 404 179
[2020-09-17 09:58:58,289] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 09:59:10,552] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 09:59:23,979] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 09:59:50,136] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 09:59:51,456] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 09:59:56,147] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:00:12,110] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:02:29,749] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:02:30,825] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:03:53,259] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 283456
[2020-09-17 10:04:33,334] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1387
[2020-09-17 10:05:03,522] [log.py:230] [log:log_response] [WARNING]- Not Found: /static/upload
[2020-09-17 10:05:03,523] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /static/upload HTTP/1.1" 404 179
[2020-09-17 10:08:31,561] [log.py:230] [log:log_response] [WARNING]- Not Found: /static/upload
[2020-09-17 10:08:31,562] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /static/upload HTTP/1.1" 404 179
[2020-09-17 10:09:00,294] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:09:01,497] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:09:15,449] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:09:16,330] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:09:18,323] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 10:10:28,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 10:10:55,549] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 10:10:55,747] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:10:56,281] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:10:59,357] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 10:11:55,166] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 10:12:15,069] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:12:15,685] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:15:45,738] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/urls.py changed, reloading.
[2020-09-17 10:15:46,595] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:15:51,619] [view.py:72] [view:get_predict_flow] [ERROR]- [22e5b87194d694ac74692f9f7e672d99]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:15:51,620] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:17:04,099] [view.py:72] [view:get_predict_flow] [ERROR]- [a34294fb7540aecc17eac806ea49f558]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:17:04,100] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:17:22,937] [view.py:72] [view:get_predict_flow] [ERROR]- [a0a8217430112c4442a4350c9abe1e26]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:17:22,938] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:17:23,456] [view.py:72] [view:get_predict_flow] [ERROR]- [6b30438ac5cd6dd7f9ae2dbefb8a1aea]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:17:23,457] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:17:23,815] [view.py:72] [view:get_predict_flow] [ERROR]- [1b1b478205c853efe84145bafffba1e9]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:17:23,815] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:18:05,870] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 10:18:06,844] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:19:41,748] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 10:19:42,591] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:19:44,544] [view.py:73] [view:get_predict_flow] [ERROR]- [1b31f0acde7efa36ebe6ff1d5624a406]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:19:44,545] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:19:45,880] [view.py:73] [view:get_predict_flow] [ERROR]- [fea1e5dcdaa7e4a9b6c78be95b482fcb]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:19:45,881] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:20:24,990] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:20:25,949] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:20:27,826] [view.py:74] [view:get_predict_flow] [ERROR]- [2b92e9268473322400a4f4289c3cc4c8]:告警文件下载失败，或者告警文件不符合要求，下载地址为line_lteFlowOfCity5Min_anshun_pingba
[2020-09-17 10:20:27,826] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 10:26:12,348] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:26:13,427] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:26:22,116] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:26:23,620] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:26:24,787] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:26:29,632] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /upload_file HTTP/1.1" 200 128
[2020-09-17 10:26:31,135] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /upload_file HTTP/1.1" 200 128
[2020-09-17 10:26:54,338] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:27:07,703] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:27:08,982] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:27:47,074] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:28:04,620] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:28:21,831] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:28:22,638] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:28:33,835] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /upload_file
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py", line 220, in FileUp
    print(request.body)
NameError: name 'req' is not defined
[2020-09-17 10:28:33,838] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /upload_file HTTP/1.1" 500 145
[2020-09-17 10:28:34,322] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:28:34,834] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:28:36,695] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:28:38,097] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:28:40,959] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:43:26,126] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:43:52,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:44:57,608] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 128
[2020-09-17 10:45:42,306] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:45:43,265] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:45:52,376] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 10:45:53,288] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 10:45:55,306] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:06:14,526] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:06:15,795] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:07:06,946] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:08:31,369] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:08:41,725] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:08:47,689] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:08:48,190] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:08:49,319] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:08:55,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:00,000] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:22,754] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:23,047] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:09:23,581] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:09:25,448] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:26,736] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:37,374] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:09:38,103] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:09:39,683] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:41,370] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:42,233] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:42,987] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:43,718] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:44,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:09:45,767] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:10:13,813] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:11:06,389] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/urls.py changed, reloading.
[2020-09-17 11:11:07,279] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:11:30,189] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/urls.py changed, reloading.
[2020-09-17 11:11:31,035] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:11:56,864] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:11:57,759] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:13:00,222] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 283456
[2020-09-17 11:14:02,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1792
[2020-09-17 11:15:08,014] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 11:16:43,197] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:17:26,178] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:17:27,123] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:18:09,811] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:18:10,950] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:18:17,608] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:18:18,157] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:35:39,330] [view.py:71] [view:get_predict_flow] [ERROR]- [e54a3a1c56ba6418991a8d40e6d96d8e]:告警文件下载失败，或者告警文件不符合要求，下载地址为static/upload/0b7ed601-12bf-4c39-9928-8aad01774245.csv
[2020-09-17 11:35:39,331] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 74
[2020-09-17 11:35:39,756] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/systen_unit.py changed, reloading.
[2020-09-17 11:35:40,382] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:37:15,079] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:37:16,047] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:37:23,647] [view.py:63] [view:get_predict_flow] [ERROR]- [99623ec1f1e8b946c037f7867bef89d8]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/99623ec1f1e8b946c037f7867bef89d8.csv
[2020-09-17 11:37:23,648] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:37:25,931] [view.py:63] [view:get_predict_flow] [ERROR]- [5ab818366540edf827b7ac52d4143dfe]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/5ab818366540edf827b7ac52d4143dfe.csv
[2020-09-17 11:37:25,932] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:38:07,563] [view.py:63] [view:get_predict_flow] [ERROR]- [5ac4421bc441cfb1b4a16fe57ddbca96]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/5ac4421bc441cfb1b4a16fe57ddbca96.csv
[2020-09-17 11:38:07,564] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:39:42,522] [view.py:63] [view:get_predict_flow] [ERROR]- [41cf81cd8dee7feb6e495ac3d76150a4]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/41cf81cd8dee7feb6e495ac3d76150a4.csv
[2020-09-17 11:39:42,523] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:39:42,887] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:39:43,742] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:39:46,844] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/24c0bd54d104ab9b4d598dd2cc7f21bd.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/24c0bd54d104ab9b4d598dd2cc7f21bd.csv
[2020-09-17 11:39:46,845] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:39:49,999] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/5b90de1da17f5e4a598bcdae58e46960.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/5b90de1da17f5e4a598bcdae58e46960.csv
[2020-09-17 11:39:50,000] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:04,676] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/636f1f5f6bbebf37652f8ad15855ece0.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/636f1f5f6bbebf37652f8ad15855ece0.csv
[2020-09-17 11:40:04,677] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:04,759] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:40:05,684] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:40:08,773] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/b7de015a058a6f427a1d9bcab5c83653.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/b7de015a058a6f427a1d9bcab5c83653.csv
[2020-09-17 11:40:08,775] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:09,987] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/44797e77caa13011c8374f1264f2f0f3.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/44797e77caa13011c8374f1264f2f0f3.csv
[2020-09-17 11:40:09,989] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:15,573] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/f48d59b99024f0989b67fedb81035266.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/f48d59b99024f0989b67fedb81035266.csv
[2020-09-17 11:40:15,576] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:16,800] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/8fd0cd485ff247bb2cd5ac8aa8c5bab4.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/8fd0cd485ff247bb2cd5ac8aa8c5bab4.csv
[2020-09-17 11:40:16,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:21,314] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/90cf4b1b5989c24af3c1a126d9857116.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/90cf4b1b5989c24af3c1a126d9857116.csv
[2020-09-17 11:40:21,315] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:40:23,829] [view.py:64] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/31ace9e803817b9d823c6baf5e48d254.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/31ace9e803817b9d823c6baf5e48d254.csv
[2020-09-17 11:40:23,830] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:41:03,078] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:41:11,445] [view.py:82] [view:get_predict_flow] [ERROR]- [42de23612a7dd0126b43a65ea725b36a]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:41:11,457] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:44:52,840] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:44:54,068] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:44:58,536] [view.py:84] [view:get_predict_flow] [ERROR]- [bf5e514c96670e3f9b50b6420aa1fdc3]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:44:58,537] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:45:04,605] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:45:09,011] [view.py:84] [view:get_predict_flow] [ERROR]- [822f4201b232afc373ec60ce600c4f8a]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:45:09,012] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:45:10,625] [view.py:84] [view:get_predict_flow] [ERROR]- [bfc302296d8c2022d6731ca0913c6c9b]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:45:10,626] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:45:22,049] [view.py:84] [view:get_predict_flow] [ERROR]- [7d567e1c030a71521d059d7ec6e62aeb]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:45:22,050] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:46:33,025] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:46:34,212] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:46:38,078] [view.py:84] [view:get_predict_flow] [ERROR]- [9ab80acf6ce9d2070bedda201136b1c4]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:46:38,081] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:46:40,313] [view.py:84] [view:get_predict_flow] [ERROR]- [1218a417e0c0883585f08f722546432c]:Expecting value: line 1 column 1 (char 0)
[2020-09-17 11:46:40,313] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:48:31,832] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:48:32,969] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:48:34,889] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/a7c3d17b886aaf166aa6d8e500f229fb.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/a7c3d17b886aaf166aa6d8e500f229fb.csv
[2020-09-17 11:48:34,890] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:48:35,947] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/39024279c9b02c0901bf735f8c189028.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/39024279c9b02c0901bf735f8c189028.csv
[2020-09-17 11:48:35,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:48:37,381] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/ae392e67758c13e95a72a20fa38afc1f.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/ae392e67758c13e95a72a20fa38afc1f.csv
[2020-09-17 11:48:37,382] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:48:38,844] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/1de9fe6a8a466c63f2c357db61502bac.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/1de9fe6a8a466c63f2c357db61502bac.csv
[2020-09-17 11:48:38,845] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:49:00,963] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/4188638ed90e7d9292a7aa28dd478fe2.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/4188638ed90e7d9292a7aa28dd478fe2.csv
[2020-09-17 11:49:00,964] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:49:01,275] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:49:02,172] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:49:06,422] [view.py:67] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/da5f098e17d6f7d78ef5bd8648e31f7d.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/da5f098e17d6f7d78ef5bd8648e31f7d.csv
[2020-09-17 11:49:06,424] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:49:08,037] [view.py:67] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/2b997792c207d840b7efb8d18e3c85fd.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/2b997792c207d840b7efb8d18e3c85fd.csv
[2020-09-17 11:49:08,039] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:50:20,354] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:50:21,632] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:50:24,902] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/8b8fa31f1a40061429a87abc2f3f0375.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/8b8fa31f1a40061429a87abc2f3f0375.csv
[2020-09-17 11:50:24,903] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:50:27,044] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/6ad5c79c867f6139bfdc6fb5373e09f8.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/6ad5c79c867f6139bfdc6fb5373e09f8.csv
[2020-09-17 11:50:27,045] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:50:41,052] [view.py:68] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/c6978c99abdcf0cd6ffd2f449b7647f1.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/c6978c99abdcf0cd6ffd2f449b7647f1.csv
[2020-09-17 11:50:41,053] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:50:41,608] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:50:42,450] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:50:44,505] [view.py:53] [view:get_predict_flow] [INFO]- [7fdc28c6a1bdf591ae2f5e20b657f2c6]:请求成功，任务开始启动
[2020-09-17 11:50:44,507] [view.py:86] [view:get_predict_flow] [ERROR]- [7fdc28c6a1bdf591ae2f5e20b657f2c6]:unsupported operand type(s) for /: 'NoneType' and 'int'
[2020-09-17 11:50:44,509] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:50:48,105] [view.py:53] [view:get_predict_flow] [INFO]- [64f3a6b4f23bf0a89138639abaf37b89]:请求成功，任务开始启动
[2020-09-17 11:50:48,106] [view.py:86] [view:get_predict_flow] [ERROR]- [64f3a6b4f23bf0a89138639abaf37b89]:unsupported operand type(s) for /: 'NoneType' and 'int'
[2020-09-17 11:50:48,107] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:50:49,531] [view.py:53] [view:get_predict_flow] [INFO]- [a9e18e8d09355c9368161cf8e5a3e0de]:请求成功，任务开始启动
[2020-09-17 11:50:49,532] [view.py:86] [view:get_predict_flow] [ERROR]- [a9e18e8d09355c9368161cf8e5a3e0de]:unsupported operand type(s) for /: 'NoneType' and 'int'
[2020-09-17 11:50:49,533] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 66
[2020-09-17 11:52:54,664] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:52:55,758] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:52:59,034] [view.py:54] [view:get_predict_flow] [INFO]- [9273a82f3207eb08b756b6c8116826ba]:请求成功，任务开始启动
[2020-09-17 11:52:59,035] [view.py:69] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/9273a82f3207eb08b756b6c8116826ba.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/9273a82f3207eb08b756b6c8116826ba.csv
[2020-09-17 11:52:59,036] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:53:23,166] [view.py:54] [view:get_predict_flow] [INFO]- [51b54eb37efab482851ca739f82abf08]:请求成功，任务开始启动
[2020-09-17 11:53:23,167] [view.py:69] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/51b54eb37efab482851ca739f82abf08.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/51b54eb37efab482851ca739f82abf08.csv
[2020-09-17 11:53:23,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:53:23,212] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:53:24,083] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:53:30,415] [view.py:53] [view:get_predict_flow] [INFO]- [f348544f181a602e2f071d9e8395492f]:请求成功，任务开始启动
[2020-09-17 11:53:30,415] [view.py:69] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/f348544f181a602e2f071d9e8395492f.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/f348544f181a602e2f071d9e8395492f.csv
[2020-09-17 11:53:30,416] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:53:33,194] [view.py:53] [view:get_predict_flow] [INFO]- [b07b18a416caf898bc6a1ff6f55fa3b2]:请求成功，任务开始启动
[2020-09-17 11:53:33,194] [view.py:69] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/b07b18a416caf898bc6a1ff6f55fa3b2.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/b07b18a416caf898bc6a1ff6f55fa3b2.csv
[2020-09-17 11:53:33,195] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:53:46,726] [view.py:53] [view:get_predict_flow] [INFO]- [067d92989566b8df3a09a67ea95f2989]:请求成功，任务开始启动
[2020-09-17 11:53:46,727] [view.py:69] [view:get_predict_flow] [ERROR]- [/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/067d92989566b8df3a09a67ea95f2989.csv]:没有告警文件下载url，或者告警文件url不合法，下载地址为/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/static/download/067d92989566b8df3a09a67ea95f2989.csv
[2020-09-17 11:53:46,728] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 81
[2020-09-17 11:53:47,294] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:53:47,846] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:53:49,680] [view.py:53] [view:get_predict_flow] [INFO]- [8f99dd058e734673f11f5cce69dc270d]:请求成功，任务开始启动
[2020-09-17 11:53:49,682] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 11:55:14,510] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 11:55:15,664] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 11:57:19,525] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 11:57:39,797] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 11:58:07,338] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 11:58:09,146] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 11:58:47,533] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1792
[2020-09-17 11:58:58,893] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 11:59:26,478] [view.py:38] [view:get_predict_flow] [INFO]- [b0fb99676955a65221b2a2eca24116aa]:请求成功，任务开始启动
[2020-09-17 11:59:26,479] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:02:39,882] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:02:40,818] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:02:44,779] [view.py:38] [view:get_predict_flow] [INFO]- [50407a63fdb6507a01d0c8b2ce56ed8e]:请求成功，任务开始启动
[2020-09-17 12:02:44,781] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:02:50,581] [view.py:38] [view:get_predict_flow] [INFO]- [a1b7109708cd1303cccbcb588c5de1ad]:请求成功，任务开始启动
[2020-09-17 12:02:50,582] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:03:14,521] [view.py:38] [view:get_predict_flow] [INFO]- [08c300f8f1c0682aa9c0a1ebdef6d78d]:请求成功，任务开始启动
[2020-09-17 12:03:14,523] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:03:14,683] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:03:15,618] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:03:17,916] [view.py:38] [view:get_predict_flow] [INFO]- [b70dac121f0eff0376cc30e5e7e432e2]:请求成功，任务开始启动
[2020-09-17 12:03:17,917] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:03:19,736] [view.py:38] [view:get_predict_flow] [INFO]- [1dbf3ee0e6de67834f5130b5d957735e]:请求成功，任务开始启动
[2020-09-17 12:03:19,737] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:04:06,266] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:04:07,231] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:04:09,569] [view.py:38] [view:get_predict_flow] [INFO]- [7fd84b953d95d10614748b96f494a84c]:请求成功，任务开始启动
[2020-09-17 12:04:09,570] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:04:10,005] [view.py:38] [view:get_predict_flow] [INFO]- [e89b03f2c72df21128da20c537416b77]:请求成功，任务开始启动
[2020-09-17 12:04:10,005] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:04:56,232] [view.py:38] [view:get_predict_flow] [INFO]- [4638c3fa3e9c8ad47313f2122412cff2]:请求成功，任务开始启动
[2020-09-17 12:04:56,233] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:04:56,549] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:04:57,146] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:05:00,479] [view.py:38] [view:get_predict_flow] [INFO]- [9a7899ca84c2feb187b87572ab6f7858]:请求成功，任务开始启动
[2020-09-17 12:05:00,480] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:05:01,967] [view.py:38] [view:get_predict_flow] [INFO]- [c8cd9c1a8a22f35f78bad3a1cec3bf4a]:请求成功，任务开始启动
[2020-09-17 12:05:01,967] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:05:02,752] [view.py:38] [view:get_predict_flow] [INFO]- [c6367a8a77ac9ddfd793e6e34f1c0a84]:请求成功，任务开始启动
[2020-09-17 12:05:02,752] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:05:03,211] [view.py:38] [view:get_predict_flow] [INFO]- [e019163251c0ece7383182f12a37dd63]:请求成功，任务开始启动
[2020-09-17 12:05:03,212] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:44:09,321] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 12:44:10,231] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:44:21,224] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:44:34,349] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:44:50,804] [view.py:42] [view:get_predict_flow] [INFO]- [c03e76eca8b0456078d0faed35cd4231]:请求成功，任务开始启动
[2020-09-17 12:44:50,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:45:00,961] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1792
[2020-09-17 12:46:08,713] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:46:10,967] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:46:22,515] [view.py:42] [view:get_predict_flow] [INFO]- [69285e9fd70bcded79fbd6db4fc44982]:请求成功，任务开始启动
[2020-09-17 12:46:22,516] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:47:39,180] [view.py:42] [view:get_predict_flow] [INFO]- [c64b87bfaf0990bfed4a0a42f0745fd1]:请求成功，任务开始启动
[2020-09-17 12:47:39,181] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:47:44,062] [view.py:42] [view:get_predict_flow] [INFO]- [ccf879ecaebd4e1e205061ae77b6ad57]:请求成功，任务开始启动
[2020-09-17 12:47:44,062] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:47:45,604] [view.py:42] [view:get_predict_flow] [INFO]- [a89dfe08c0c4397c0e734a6ef771f871]:请求成功，任务开始启动
[2020-09-17 12:47:45,605] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:48:52,833] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 12:48:53,767] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:49:03,527] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 12:49:04,382] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:49:07,345] [view.py:45] [view:get_predict_flow] [INFO]- [69a57f322a66b31bae05a26e4a1976e6]:请求成功，任务开始启动
[2020-09-17 12:49:07,347] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:49:15,526] [view.py:45] [view:get_predict_flow] [INFO]- [d1cb2497369e574de091d7b647234c61]:请求成功，任务开始启动
[2020-09-17 12:49:15,526] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:49:17,535] [view.py:45] [view:get_predict_flow] [INFO]- [d59b5066235d1e596a67d3e9a3ff7324]:请求成功，任务开始启动
[2020-09-17 12:49:17,536] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:49:19,041] [view.py:45] [view:get_predict_flow] [INFO]- [67f36c9965bd00f6208b4a779e78079e]:请求成功，任务开始启动
[2020-09-17 12:49:19,042] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:49:20,162] [view.py:45] [view:get_predict_flow] [INFO]- [38689d7ec70ac444ebf3d478d7a5f4e4]:请求成功，任务开始启动
[2020-09-17 12:49:20,163] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:49:21,012] [view.py:45] [view:get_predict_flow] [INFO]- [bbca1d406f143a89d8f82c5d08dd0135]:请求成功，任务开始启动
[2020-09-17 12:49:21,013] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 243
[2020-09-17 12:51:13,619] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 12:51:14,285] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:51:18,349] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:51:23,005] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:51:34,523] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:51:34,524] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:52:02,927] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:52:02,928] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:52:03,905] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:52:03,905] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:52:04,585] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:52:04,586] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:52:12,671] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:52:15,588] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:52:39,769] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:52:41,874] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:52:58,850] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:52:59,902] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:53:09,334] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1792
[2020-09-17 12:53:56,203] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 12:54:35,009] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:55:18,784] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:55:18,786] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:56:34,966] [view.py:46] [view:get_predict_flow] [INFO]- [0b8c9dcd-7227-42f6-bb68-d6963f7e75f1]:请求成功，任务开始启动
[2020-09-17 12:56:34,967] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:56:35,280] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:56:35,977] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:56:39,947] [view.py:46] [view:get_predict_flow] [INFO]- [a7d2de1d-958d-416c-8e71-57f8cb1ef639]:请求成功，任务开始启动
[2020-09-17 12:56:39,949] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:56:45,383] [view.py:46] [view:get_predict_flow] [INFO]- [a7d2de1d-958d-416c-8e71-57f8cb1ef639]:请求成功，任务开始启动
[2020-09-17 12:56:45,384] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:57:14,567] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 12:57:15,373] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:57:17,270] [view.py:46] [view:get_predict_flow] [INFO]- [970673f1-7905-48f8-a22a-c668fc1570b6]:请求成功，任务开始启动
[2020-09-17 12:57:17,271] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:57:20,069] [view.py:46] [view:get_predict_flow] [INFO]- [970673f1-7905-48f8-a22a-c668fc1570b6]:请求成功，任务开始启动
[2020-09-17 12:57:20,070] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:58:03,239] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:58:08,447] [view.py:46] [view:get_predict_flow] [INFO]- [970673f1-7905-48f8-a22a-c668fc1570b6]:请求成功，任务开始启动
[2020-09-17 12:58:08,447] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 12:59:06,499] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 12:59:08,662] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 12:59:14,628] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 12:59:32,816] [view.py:46] [view:get_predict_flow] [INFO]- [1454b8f7-70ce-4e80-a8d4-244e1392118f]:请求成功，任务开始启动
[2020-09-17 12:59:32,816] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:00:01,879] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 347
[2020-09-17 13:00:31,262] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/core/warn_realation.py changed, reloading.
[2020-09-17 13:00:31,885] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:00:36,396] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:00:45,836] [view.py:46] [view:get_predict_flow] [INFO]- [c1efc914-cf65-4e0a-92cd-0ac3b0785cb3]:请求成功，任务开始启动
[2020-09-17 13:00:45,840] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:00:50,104] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 347
[2020-09-17 13:02:23,664] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 13:02:24,803] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:02:27,385] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:02:31,427] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:02:32,453] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:02:36,627] [view.py:43] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:02:36,667] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:02:40,761] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 347
[2020-09-17 13:02:41,905] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 347
[2020-09-17 13:02:45,716] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:02:48,437] [view.py:43] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:02:48,438] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:02:50,885] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 347
[2020-09-17 13:03:28,294] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:03:33,960] [view.py:43] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:03:33,961] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:03:37,352] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:03:47,009] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:03:59,959] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:04:04,232] [view.py:43] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:04:04,233] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:04:22,647] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 716
[2020-09-17 13:07:17,793] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 13:07:18,513] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:07:46,013] [view.py:46] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:07:46,015] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:07:48,743] [view.py:46] [view:get_predict_flow] [INFO]- [5194853c-ad8f-4c46-972d-34dbcb2bb0ce]:请求成功，任务开始启动
[2020-09-17 13:07:48,744] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:08:04,562] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1416
[2020-09-17 13:08:09,068] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 13:08:10,208] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:08:20,380] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:08:27,877] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 133
[2020-09-17 13:08:49,667] [view.py:46] [view:get_predict_flow] [INFO]- [18c4a155-cd92-4b95-a98d-7a20fc39d96a]:请求成功，任务开始启动
[2020-09-17 13:08:49,670] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:09:03,871] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:09:07,342] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:09:08,280] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:09:09,898] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-09-17 13:09:15,598] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 353
[2020-09-17 13:14:45,635] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/warn_relaction_interface/view.py changed, reloading.
[2020-09-17 13:14:46,653] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-09-17 13:14:51,008] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-09-17 13:15:53,085] [view.py:46] [view:get_predict_flow] [INFO]- [ba5ba4e6-4264-43a9-b9bf-e390c59899fb]:请求成功，任务开始启动
[2020-09-17 13:15:53,090] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:17:48,928] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 364
[2020-09-17 13:18:26,023] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 364
[2020-09-17 13:20:01,955] [view.py:46] [view:get_predict_flow] [INFO]- [ba5ba4e6-4264-43a9-b9bf-e390c59899fb]:请求成功，任务开始启动
[2020-09-17 13:20:01,956] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 13:20:04,722] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 728
[2020-09-17 13:22:06,330] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 13:22:08,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 14:31:55,049] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 67
[2020-09-17 14:31:55,629] [log.py:230] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-09-17 14:31:55,629] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 179
[2020-09-17 14:32:17,563] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-09-17 14:32:48,742] [view.py:46] [view:get_predict_flow] [INFO]- [ba5ba4e6-4264-43a9-b9bf-e390c59899fb]:请求成功，任务开始启动
[2020-09-17 14:32:48,743] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 14:32:53,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1076
[2020-09-17 14:32:56,514] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 14:35:04,835] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-09-17 14:35:08,414] [view.py:46] [view:get_predict_flow] [INFO]- [ba5ba4e6-4264-43a9-b9bf-e390c59899fb]:请求成功，任务开始启动
[2020-09-17 14:35:08,416] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 14:35:10,210] [view.py:46] [view:get_predict_flow] [INFO]- [ba5ba4e6-4264-43a9-b9bf-e390c59899fb]:请求成功，任务开始启动
[2020-09-17 14:35:10,210] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 251
[2020-09-17 14:35:13,156] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1763
[2020-09-17 14:35:14,563] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1763
[2020-09-17 14:35:16,606] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-09-17 14:35:17,597] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
