[2020-10-12 16:28:36,554] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:29:01,228] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:29:25,881] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:29:25,882] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:31:07,113] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_day.py changed, reloading.
[2020-10-12 16:31:07,842] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:31:18,518] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:31:18,519] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:33:19,419] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_day.py changed, reloading.
[2020-10-12 16:33:20,189] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:33:31,093] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:33:31,094] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:33:59,348] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:33:59,349] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:35:13,708] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:35:30,912] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:35:30,933] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:35:55,821] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:35:55,828] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:37:00,224] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_day.py changed, reloading.
[2020-10-12 16:37:01,016] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:37:16,395] [view.py:55] [view:get_predict_flow] [INFO]- [8de52a69-c58c-4b32-b976-cef58d7be20a]:请求成功，任务开始启动
[2020-10-12 16:37:16,396] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:39:09,240] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:41:45,642] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-12 16:41:47,006] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:42:52,836] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_min.py changed, reloading.
[2020-10-12 16:42:53,628] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:42:55,709] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:43:13,427] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:43:26,437] [view.py:55] [view:get_predict_flow] [INFO]- [6c7b7768-af6d-4cc1-9f2a-49230d51b529]:请求成功，任务开始启动
[2020-10-12 16:43:26,438] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 193
[2020-10-12 16:47:03,515] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:47:05,753] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:47:21,601] [view.py:55] [view:get_predict_flow] [INFO]- [6c7b7768-af6d-4cc1-9f2a-49230d51b529]:请求成功，任务开始启动
[2020-10-12 16:47:21,603] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:47:37,944] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/6c7b7768-af6d-4cc1-9f2a-49230d51b529.csv HTTP/1.1" 200 1258
[2020-10-12 16:48:08,110] [view.py:55] [view:get_predict_flow] [INFO]- [6c7b7768-af6d-4cc1-9f2a-49230d51b529]:请求成功，任务开始启动
[2020-10-12 16:48:08,111] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:48:13,174] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/6c7b7768-af6d-4cc1-9f2a-49230d51b529.csv HTTP/1.1" 200 629
[2020-10-12 16:48:24,449] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 311
[2020-10-12 16:48:29,153] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 311
[2020-10-12 16:49:44,402] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:49:45,510] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:50:00,016] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding=utf - 8) as file:
NameError: name 'utf' is not defined
[2020-10-12 16:50:00,019] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:50:01,728] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding=utf - 8) as file:
NameError: name 'utf' is not defined
[2020-10-12 16:50:01,729] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:50:03,078] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding=utf - 8) as file:
NameError: name 'utf' is not defined
[2020-10-12 16:50:03,079] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:50:24,961] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:50:25,914] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:50:33,232] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding=utf-8) as file:
NameError: name 'utf' is not defined
[2020-10-12 16:50:33,234] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:50:34,439] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding=utf-8) as file:
NameError: name 'utf' is not defined
[2020-10-12 16:50:34,440] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:50:43,165] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:50:44,149] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:51:00,068] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:51:01,049] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:51:11,036] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding='utf-8') as file:
ValueError: binary mode doesn't take an encoding argument
[2020-10-12 16:51:11,038] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:51:12,608] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding='utf-8') as file:
ValueError: binary mode doesn't take an encoding argument
[2020-10-12 16:51:12,619] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:51:13,454] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /get_download_resu
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Applications/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py", line 171, in FileDown
    with open(os.path.join(file_path, work_id + ".csv"), 'rb', encoding='utf-8') as file:
ValueError: binary mode doesn't take an encoding argument
[2020-10-12 16:51:13,455] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /get_download_resu HTTP/1.1" 500 145
[2020-10-12 16:51:45,284] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 16:51:46,307] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:51:54,693] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 311
[2020-10-12 16:51:57,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 311
[2020-10-12 16:53:27,287] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:53:38,439] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:53:50,089] [view.py:55] [view:get_predict_flow] [INFO]- [bd95b718-0333-458d-bc75-7a6fd9d224ca]:请求成功，任务开始启动
[2020-10-12 16:53:50,092] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:54:27,627] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 16:54:37,186] [view.py:55] [view:get_predict_flow] [INFO]- [bd95b718-0333-458d-bc75-7a6fd9d224ca]:请求成功，任务开始启动
[2020-10-12 16:54:37,208] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:55:17,805] [view.py:55] [view:get_predict_flow] [INFO]- [bd95b718-0333-458d-bc75-7a6fd9d224ca]:请求成功，任务开始启动
[2020-10-12 16:55:17,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:55:31,288] [view.py:55] [view:get_predict_flow] [INFO]- [bd95b718-0333-458d-bc75-7a6fd9d224ca]:请求成功，任务开始启动
[2020-10-12 16:55:31,289] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:55:44,229] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1235
[2020-10-12 16:55:51,010] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-12 16:55:56,588] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/bd95b718-0333-458d-bc75-7a6fd9d224ca.csv HTTP/1.1" 200 1887
[2020-10-12 16:56:05,078] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:56:26,215] [view.py:55] [view:get_predict_flow] [INFO]- [bd95b718-0333-458d-bc75-7a6fd9d224ca]:请求成功，任务开始启动
[2020-10-12 16:56:26,216] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:56:27,981] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:56:45,709] [view.py:55] [view:get_predict_flow] [INFO]- [eacd4739-ecff-490d-b82d-5cce1f0dee80]:请求成功，任务开始启动
[2020-10-12 16:56:45,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:57:31,968] [view.py:55] [view:get_predict_flow] [INFO]- [eacd4739-ecff-490d-b82d-5cce1f0dee80]:请求成功，任务开始启动
[2020-10-12 16:57:31,970] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 16:57:44,765] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 684
[2020-10-12 16:57:55,832] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-12 16:57:58,421] [log.py:230] [log:log_response] [WARNING]- Not Found: /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80csv
[2020-10-12 16:57:58,422] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80csv HTTP/1.1" 404 179
[2020-10-12 16:58:01,121] [log.py:230] [log:log_response] [WARNING]- Not Found: /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80csv
[2020-10-12 16:58:01,122] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80csv HTTP/1.1" 404 179
[2020-10-12 16:58:09,517] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80.csv HTTP/1.1" 200 1251
[2020-10-12 16:58:20,799] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80.csv HTTP/1.1" 200 1251
[2020-10-12 16:58:21,727] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/eacd4739-ecff-490d-b82d-5cce1f0dee80.csv HTTP/1.1" 200 1251
[2020-10-12 16:58:29,885] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 16:58:52,436] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 84
[2020-10-12 16:59:00,738] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 82
[2020-10-12 16:59:21,878] [view.py:55] [view:get_predict_flow] [INFO]- [095918e7-b2f0-421c-a333-3c5e706a7cf9]:请求成功，任务开始启动
[2020-10-12 16:59:21,879] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 17:00:24,083] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 17:00:25,928] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 17:00:35,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 298
[2020-10-12 17:00:39,370] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 298
[2020-10-12 17:00:40,765] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 298
[2020-10-12 17:02:13,147] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/core/predict_hour.py changed, reloading.
[2020-10-12 17:02:14,219] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 21:35:05,073] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 21:35:37,245] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 21:36:29,767] [view.py:55] [view:get_predict_flow] [INFO]- [021448fc-df6d-4723-8912-e66ffad235c8]:请求成功，任务开始启动
[2020-10-12 21:36:29,768] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 21:36:58,724] [view.py:55] [view:get_predict_flow] [INFO]- [021448fc-df6d-4723-8912-e66ffad235c8]:请求成功，任务开始启动
[2020-10-12 21:36:58,725] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 21:37:02,306] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1868
[2020-10-12 21:37:11,297] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-12 21:37:25,849] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/021448fc-df6d-4723-8912-e66ffad235c8.csv HTTP/1.1" 200 1868
[2020-10-12 21:37:39,772] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 21:38:09,086] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 96
[2020-10-12 21:38:20,116] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 95
[2020-10-12 21:38:31,244] [view.py:55] [view:get_predict_flow] [INFO]- [6a5d375c-1b31-4fcf-b6af-58bd0e72be83]:请求成功，任务开始启动
[2020-10-12 21:38:31,245] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 21:38:36,520] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1256
[2020-10-12 21:38:39,825] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-12 21:38:59,687] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/download/6a5d375c-1b31-4fcf-b6af-58bd0e72be83.csv HTTP/1.1" 200 1256
[2020-10-12 21:39:08,634] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /upload_file HTTP/1.1" 200 184
[2020-10-12 21:39:26,287] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 96
[2020-10-12 21:39:34,713] [view.py:55] [view:get_predict_flow] [INFO]- [08dfac3d-44fc-43c0-9387-296e8e6f3e75]:请求成功，任务开始启动
[2020-10-12 21:39:34,715] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 21:41:42,459] [autoreload.py:236] [autoreload:trigger_reload] [INFO]- /Users/fengdong/PycharmProjects/flowpredict000/flowpredict/flow_predict_interface/view.py changed, reloading.
[2020-10-12 21:41:44,371] [autoreload.py:612] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-10-12 21:42:10,365] [view.py:55] [view:get_predict_flow] [INFO]- [08dfac3d-44fc-43c0-9387-296e8e6f3e75]:请求成功，任务开始启动
[2020-10-12 21:42:10,367] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_flow HTTP/1.1" 200 192
[2020-10-12 21:42:17,562] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_download_resu HTTP/1.1" 200 1258
[2020-10-12 21:42:21,552] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
[2020-10-12 21:42:26,883] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /get_resu_process HTTP/1.1" 200 81
